// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phmitrmyurzwkizvohxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBobWl0cm15dXJ6d2tpenZvaHh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MTAxMzksImV4cCI6MjA2NTA4NjEzOX0.wIHD6c8-GyVOkReZt5Ma2JHAwVZ5WE-Sr_JHrErU6vc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);